---
title: "Eliminación Gaussiana por pivoteo parcial"
author: "Jiménez Avilés Jhovany"
date: "`r format(Sys.time(), '%d %B, %Y')`"
output:
  html_document:
    toc: true
    toc_float: true
    toc_depth: 3
    code_folding: show
    theme: bootstrap
  word_document: default
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
## Eliminación Gauuseana con pivoteo parcial

## el sistema a resolver es:
## 5x+2y-3z+4w=-1
## -x+y+z-3w=2
## 6x+6y-4z+w=0
## x-y-z+w=2

```{r}
valores<-c(5,2,-3,4,-1,1,1,-3,6,6,-4,1,1,-1,-1,1)
A<-matrix(valores,nrow = 4); (A)
A<-t(A);(A)
B<-c(-1,2,0,2)
AB<-cbind(A,B); (AB)
```

```{r}
R1<-A[3,]
R3<-A[1,]
R2<-A[2,]
R4<-A[4,]
nuevaA<-rbind(R1,R2,R3,R4); (nuevaA)

```

```{r}
AB<-nuevaA; (AB)
m1<- -AB[2,1]/AB[1.1]; (m1)
m2<-  AB[3,1]/AB[1.1];(m2)
m3<-  AB[4,1]/AB[1,1]; (m3)

```

```{r}
R1<-AB[1,]
R2<- m1*AB[1,]+AB[2,]; (R2)
R3<- m2*AB[1,]+AB[3,]; (R3)
R4<- m3*AB[1,]+AB[4,]; (R4)
```

```{r}
nuevaA<-rbind(R1,R2,R3,R4);(nuevaA)
```

```{r}
R1<-nuevaA[1,];
R2<-nuevaA[3,];
R3<-nuevaA[2,];
R4<-nuevaA[4,];
AB<-rbind(R1,R2,R3,R4); (AB)
```

```{r}
m4<- -AB[3,2]/AB[2,2];
m5<- -AB[4,2]/AB[2,2];
R3<- m4*AB[2,]+AB[3,]; (R3)
R4<- m5*AB[2,]+AB[4,];(R4)

nuevaA<-rbind(R1,R2,R3,R4); (nuevaA)

```

```{r}
m6<- -nuevaA[4,3]/nuevaA[3,3]
R1<- nuevaA[1,]
R2<- nuevaA[2,]
R3<- nuevaA[3,]
R4<- m6*nuevaA[3,]+nuevaA[4,]
nuevaA<- rbind(R1,R2,R3,R4)
(nuevaA)

```

```{r}
m7<- -nuevaA[3,4]/nuevaA[4,4]
m8<- -nuevaA[2,4]/nuevaA[4,4]
m9<- -nuevaA[1,4]/nuevaA[4,4]

R1<- m9*nuevaA[4,]+nuevaA[1,]
R2<- m8 * nuevaA[4,] + nuevaA[2,]
R3<- m7 * nuevaA[4,] + nuevaA[3,]
R4<- nuevaA[4,]

nuevaA<- rbind(R1,R2,R3,R4)
(nuevaA)
```

```{r}
m10<- -nuevaA[2,3]/nuevaA[3,3]
m11<- -nuevaA[1,3]/nuevaA[3,3]

R4<- nuevaA[4,]
R3<- nuevaA[3,]
R2<- m10 * nuevaA[3,] + nuevaA[2,]
R1<- m11 * nuevaA[3,] + nuevaA[1,]

nuevaA<- rbind(R1,R2,R3,R4)
(nuevaA)
```

```{r}
m12<- -nuevaA[1,2]/nuevaA[2,2]

R4<- nuevaA[4,]
R3<- nuevaA[3,]
R2<- nuevaA[2,]
R1<- m12 * nuevaA[2,] + nuevaA[1,]

nuevaA<- rbind(R1,R2,R3,R4)
(nuevaA)
```







