---
title: "sesiones proba"
output: html_document
date: "2025-09-03"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# ejemplos del uso del comando "for"

```{r}
# n_try es la cantidad de veces que voy a repetir el proceso
n_try<-10
lista<- c()
for (i in 1: n_try){
  lista[i]<-i^2;
  print(lista[i])
}
(lista)
```

se van agenerar los primeros 10, cuadrados, cubos, cuarta y quinta potencia de los primeros 10 números naturales.

```{r}
n_try<-10;
potencias<-5
matriz_potencias<-matrix(0,n_try,potencias);
(matriz_potencias)

```

```{r}
for (i in 1: n_try) {
  for (j in 1: potencias) {
    matriz_potencias[i,j]<- i^j
    print(matriz_potencias[i,j])
   
  }
 
}
print(matriz_potencias)

```

ponemos nombres a las columnas
```{r}
colnames(matriz_potencias)<-c("n","cuadrado","cubo","cuarta","quinta")
(matriz_potencias)

```

ponemos nombres a los renglones

```{r}
row.names(matriz_potencias)<-c("n-1","n-2","n-3","n-4","n-5","n-6","n-7","n-8","n-9","n-10")
(matriz_potencias)

```

```{r}
medias<-c()
medias[1]<-mean(matriz_potencias[1,])
medias[2]<-mean(matriz_potencias[2,])
medias[3]<-mean(matriz_potencias[3,])
medias[4]<-mean(matriz_potencias[4,])
medias[5]<-mean(matriz_potencias[5,])
medias[6]<-mean(matriz_potencias[6,])
medias[7]<-mean(matriz_potencias[7,])
medias[8]<-mean(matriz_potencias[8,])
medias[9]<-mean(matriz_potencias[9,])
medias[10]<-mean(matriz_potencias[10,])
(medias)

```

ahora calculamos las medias de las columnas

```{r}
medias_col<-c()
medias_col[1]<-mean(matriz_potencias[1,])
medias_col[2]<-mean(matriz_potencias[2,])
medias_col[3]<-mean(matriz_potencias[3,])
medias_col[4]<-mean(matriz_potencias[4,])
medias_col[5]<-mean(matriz_potencias[5,])
print(medias_col)
```

```{r}
vector_medias_columna<-c()
for ( i in 1:potencias) {
  vector_medias_columna[i]<-mean(matriz_potencias[i])
  print(vector_medias_columna[i])
}
print(vector_medias_columna)

```

ahora por renglon

```{r}
vector_medias_renglon<-c()
for (i in 1:n_try) {
vector_medias_renglon[i]<-mean(matriz_potencias[i,])
  print(vector_medias_renglon[i])
}
print(vector_medias_renglon)
```

```{r}
vector_sd_renglon<-c()
vector_sd_columna<-c()

```
